apiVersion: apps/v1
kind: ReplicaSet
metadata:   
 name: myreplica  
spec:       
 replicas: 6
 selector:  
  matchLabels:
    release: alpha
 template:  
  metadata: 
   labels:  
     release: alpha          
  spec:     
   containers:
   - name: xyz
    image: quay.io/shruti1988/webapp
    imagePullPolicy: IfNotPresent
